/* This file is generated by scripts/generate-registry.mjs. Do not edit. */
import type {AnimationModule} from './contract';

export type AnimationModuleLoader = () => Promise<AnimationModule>;

export const animationModuleLoaders: Readonly<Record<string, AnimationModuleLoader>> = Object.freeze({
  'conversion-1-2': () => import('./modules/conversion-1-2').then(({default: animationModule}) => animationModule),
  'conversion-1-4': () => import('./modules/conversion-1-4').then(({default: animationModule}) => animationModule)
});
