/* This file is generated by scripts/generate-registry.mjs. Do not edit. */
import type {AnimationModule} from './contract';

export type AnimationModuleLoader = () => Promise<AnimationModule>;

export const animationModuleLoaders: Readonly<Record<string, AnimationModuleLoader>> = Object.freeze({

});
